### PR TITLE
Fix #181

### LINKED ISSUE #181: [Bug] Putting item in anvil causes game to crash, 'material' is 'null' (1.21)
### What happened?

When me and my other friend were trying out mods and trying to see if everything worked well, whenever we placed any item into the anvil it crashes every time. We checked if it was other mods making it that way but it would always lead to BCLib being the problem.

### BCLib

21.0.3

### Fabric API

0.100.4+1.21

### Fabric Loader

1.0.1

### Minecraft

1.20.4

### Relevant log output

```shell
The game crashed whilst container click
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7947()" because "material" is null
```

### Other Mods

_No response_

### PR DESCRIPTION
**Pull request by OffsetMonkey538**
Might need testing

### CODE REVIEW

**Comment by cutekita** [comment]
Testing this out in a few minutes, ran into this crash a few minutes ago

**Comment by KennyDevT** [comment]
I can confirm this works

**Comment by cutekita** [comment]
> I can confirm this works

could you tell me how you built this? ive been failing over and over again because of different things

**Comment by KennyDevT** [comment]
So Basically you have to make a folder that keeps all the repos separate mine is called BetterXHome. Then you git clone the 1.21 branch of WorldWeaver. After that, you cd into the WorldWeaver Folder and git clone the 1.21 branch of Wunder Lib. Then in the WorldWeaver folder you execute the command `gradlew build`. Then when its finished cd out of the WorldWeaver and enter this pr branch of BCLib. In the BCLib folder you open the settings.gradle file and set the `allowLocalLibInConsoleMode` to true.

**Comment by cutekita** [comment]
Thank you, this seemed to have worked, very silly!

The fix definitely works perfectly fine for me! (although my latest crash deleted my diamond helment :/)

**Comment by OffsetMonkey538** [comment]
Yeah, might be worth adding annotations like `@Nullable` when a method can return null as then your IDE will probably warn about issues like this.

Anyway I think the fix might need to be implemented on older versions as well, but I'm not sure how to do this as I don't want to make multiple PRs for this as that seems annoying and wrong for an issue this small xD

**Comment by OffsetMonkey538** [comment]
Seems to be fixed in https://github.com/quiqueck/BCLib/commit/f20b4f2fab1360ecdf90225a12d874aa874d26f7

**Pull request closed without merging**
